/**
  * 功能：数据结构
  * 作者：费俊程
  * 创建日期：2018.12.21：16.16
  */
package com.security

case class Gprs(USER_NUMBER :String, START_TIME :String, ROAM_VOLUME :Long, LOCAL_VOLUME :Long,
                ROAM_COUNT :Long, LOCAL_COUNT :Long, ROAM_DURATION :Long, LOCAL_DURATION :Long,
                FLOW_00_COUNT :Long, FLOW_01_COUNT :Long, FLOW_02_COUNT :Long, FLOW_03_COUNT :Long,
                FLOW_04_COUNT :Long, FLOW_05_COUNT :Long, FLOW_06_COUNT :Long, FLOW_07_COUNT :Long,
                FLOW_08_COUNT :Long, FLOW_09_COUNT :Long, FLOW_10_COUNT :Long, FLOW_11_COUNT :Long,
                FLOW_00_UP_VOLUME :Long, FLOW_01_UP_VOLUME :Long, FLOW_02_UP_VOLUME :Long,
                FLOW_03_UP_VOLUME :Long, FLOW_04_UP_VOLUME :Long, FLOW_05_UP_VOLUME :Long,
                FLOW_06_UP_VOLUME :Long, FLOW_07_UP_VOLUME :Long, FLOW_08_UP_VOLUME :Long,
                FLOW_09_UP_VOLUME :Long, FLOW_10_UP_VOLUME :Long, FLOW_11_UP_VOLUME :Long,
                FLOW_00_DOWN_VOLUME :Long, FLOW_01_DOWN_VOLUME :Long, FLOW_02_DOWN_VOLUME :Long,
                FLOW_03_DOWN_VOLUME :Long, FLOW_04_DOWN_VOLUME :Long, FLOW_05_DOWN_VOLUME :Long,
                FLOW_06_DOWN_VOLUME :Long, FLOW_07_DOWN_VOLUME :Long, FLOW_08_DOWN_VOLUME :Long,
                FLOW_09_DOWN_VOLUME :Long, FLOW_10_DOWN_VOLUME :Long, FLOW_11_DOWN_VOLUME :Long,
                FLOW_00_2G_UP_VOLUME :Long, FLOW_01_2G_UP_VOLUME :Long, FLOW_02_2G_UP_VOLUME :Long,
                FLOW_03_2G_UP_VOLUME :Long, FLOW_04_2G_UP_VOLUME :Long, FLOW_05_2G_UP_VOLUME :Long,
                FLOW_06_2G_UP_VOLUME :Long, FLOW_07_2G_UP_VOLUME :Long, FLOW_08_2G_UP_VOLUME :Long,
                FLOW_09_2G_UP_VOLUME :Long, FLOW_10_2G_UP_VOLUME :Long, FLOW_11_2G_UP_VOLUME :Long,
                FLOW_00_2G_DOWN_VOLUME :Long, FLOW_01_2G_DOWN_VOLUME :Long, FLOW_02_2G_DOWN_VOLUME :Long,
                FLOW_03_2G_DOWN_VOLUME :Long, FLOW_04_2G_DOWN_VOLUME :Long, FLOW_05_2G_DOWN_VOLUME :Long,
                FLOW_06_2G_DOWN_VOLUME :Long, FLOW_07_2G_DOWN_VOLUME :Long, FLOW_08_2G_DOWN_VOLUME :Long,
                FLOW_09_2G_DOWN_VOLUME :Long, FLOW_10_2G_DOWN_VOLUME :Long, FLOW_11_2G_DOWN_VOLUME :Long,
                FLOW_00_3G_UP_VOLUME :Long, FLOW_01_3G_UP_VOLUME :Long, FLOW_02_3G_UP_VOLUME :Long,
                FLOW_03_3G_UP_VOLUME :Long, FLOW_04_3G_UP_VOLUME :Long, FLOW_05_3G_UP_VOLUME :Long,
                FLOW_06_3G_UP_VOLUME :Long, FLOW_07_3G_UP_VOLUME :Long, FLOW_08_3G_UP_VOLUME :Long,
                FLOW_09_3G_UP_VOLUME :Long, FLOW_10_3G_UP_VOLUME :Long, FLOW_11_3G_UP_VOLUME :Long,
                FLOW_00_3G_DOWN_VOLUME :Long, FLOW_01_3G_DOWN_VOLUME :Long, FLOW_02_3G_DOWN_VOLUME :Long,
                FLOW_03_3G_DOWN_VOLUME :Long, FLOW_04_3G_DOWN_VOLUME :Long, FLOW_05_3G_DOWN_VOLUME :Long,
                FLOW_06_3G_DOWN_VOLUME :Long, FLOW_07_3G_DOWN_VOLUME :Long, FLOW_08_3G_DOWN_VOLUME :Long,
                FLOW_09_3G_DOWN_VOLUME :Long, FLOW_10_3G_DOWN_VOLUME :Long, FLOW_11_3G_DOWN_VOLUME :Long,
                FLOW_00_4G_UP_VOLUME :Long, FLOW_01_4G_UP_VOLUME :Long, FLOW_02_4G_UP_VOLUME :Long,
                FLOW_03_4G_UP_VOLUME :Long, FLOW_04_4G_UP_VOLUME :Long, FLOW_05_4G_UP_VOLUME :Long,
                FLOW_06_4G_UP_VOLUME :Long, FLOW_07_4G_UP_VOLUME :Long, FLOW_08_4G_UP_VOLUME :Long,
                FLOW_09_4G_UP_VOLUME :Long, FLOW_10_4G_UP_VOLUME :Long, FLOW_11_4G_UP_VOLUME :Long,
                FLOW_00_4G_DOWN_VOLUME :Long, FLOW_01_4G_DOWN_VOLUME :Long, FLOW_02_4G_DOWN_VOLUME :Long,
                FLOW_03_4G_DOWN_VOLUME :Long, FLOW_04_4G_DOWN_VOLUME :Long, FLOW_05_4G_DOWN_VOLUME :Long,
                FLOW_06_4G_DOWN_VOLUME :Long, FLOW_07_4G_DOWN_VOLUME :Long, FLOW_08_4G_DOWN_VOLUME :Long,
                FLOW_09_4G_DOWN_VOLUME :Long, FLOW_10_4G_DOWN_VOLUME :Long, FLOW_11_4G_DOWN_VOLUME :Long)


case class Sms(USER_NUMBER :String, START_TIME :String, SEND_MESSAGE_COUNT :Long,
               SMS_00_VOLUME :Long, SMS_01_VOLUME :Long, SMS_02_VOLUME :Long,
               SMS_03_VOLUME :Long, SMS_04_VOLUME :Long, SMS_05_VOLUME :Long,
               SMS_06_VOLUME :Long, SMS_07_VOLUME :Long, SMS_08_VOLUME :Long,
               SMS_09_VOLUME :Long, SMS_10_VOLUME :Long, SMS_11_VOLUME :Long)

case class Voice(USER_NUMBER:String,START_TIME:String,CALL_VOLUME:Long,CALLED_VOLUME:Long,
                 CALL_COUNT:Long,CALLED_COUNT:Long,CALL_00_COUNT:Long,CALL_01_COUNT:Long,
                 CALL_02_COUNT:Long,CALL_03_COUNT:Long,CALL_04_COUNT:Long,
                 CALL_05_COUNT:Long,CALL_06_COUNT:Long,CALL_07_COUNT:Long,
                 CALL_08_COUNT:Long,CALL_09_COUNT:Long,CALL_10_COUNT:Long,
                 CALL_11_COUNT:Long,CALLED_00_COUNT:Long,CALLED_01_COUNT:Long,
                 CALLED_02_COUNT:Long,CALLED_03_COUNT:Long,CALLED_04_COUNT:Long,
                 CALLED_05_COUNT:Long,CALLED_06_COUNT:Long,CALLED_07_COUNT:Long,
                 CALLED_08_COUNT:Long,CALLED_09_COUNT:Long,CALLED_10_COUNT:Long,
                 CALLED_11_COUNT:Long,CALL_00_VOLUME:Long,CALL_01_VOLUME:Long,
                 CALL_02_VOLUME:Long,CALL_03_VOLUME:Long,CALL_04_VOLUME:Long,
                 CALL_05_VOLUME:Long,CALL_06_VOLUME:Long,CALL_07_VOLUME:Long,
                 CALL_08_VOLUME:Long,CALL_09_VOLUME:Long,CALL_10_VOLUME:Long,
                 CALL_11_VOLUME:Long,CALLED_00_VOLUME:Long,CALLED_01_VOLUME:Long,
                 CALLED_02_VOLUME:Long,CALLED_03_VOLUME:Long,CALLED_04_VOLUME:Long,
                 CALLED_05_VOLUME:Long,CALLED_06_VOLUME:Long,CALLED_07_VOLUME:Long,
                 CALLED_08_VOLUME:Long,CALLED_09_VOLUME:Long,CALLED_10_VOLUME:Long,
                 CALLED_11_VOLUME:Long)

case class ImeiData(date:String,num:String,imei:String,province:String,city:String,tag:Int)


case class MonthGprs(USER_NUMBER:String,RECENT_30_DAY_COUNT:Long,RECENT_30_COUNT:Long,
                     RECENT_30_ROAM_VOLUME:Long,RECENT_30_LOCAL_VOLUME:Long,RECENT_30_ROAM_COUNT:Long,
                     RECENT_30_LOCAL_COUNT:Long,RECENT_30_ROAM_DURATION:Long,RECENT_30_LOCAL_DURATION:Long,
                     RECENT_30_00_COUNT:Long,RECENT_30_01_COUNT:Long,RECENT_30_02_COUNT:Long,
                     RECENT_30_03_COUNT:Long,RECENT_30_04_COUNT:Long,RECENT_30_05_COUNT:Long,
                     RECENT_30_06_COUNT:Long,RECENT_30_07_COUNT:Long,RECENT_30_08_COUNT:Long,
                     RECENT_30_09_COUNT:Long,RECENT_30_10_COUNT:Long,RECENT_30_11_COUNT:Long,
                     RECENT_30_00_UP_VOLUME:Long,RECENT_30_01_UP_VOLUME:Long,RECENT_30_02_UP_VOLUME:Long,
                     RECENT_30_03_UP_VOLUME:Long,RECENT_30_04_UP_VOLUME:Long,RECENT_30_05_UP_VOLUME:Long,
                     RECENT_30_06_UP_VOLUME:Long,RECENT_30_07_UP_VOLUME:Long,RECENT_30_08_UP_VOLUME:Long,
                     RECENT_30_09_UP_VOLUME:Long,RECENT_30_10_UP_VOLUME:Long,RECENT_30_11_UP_VOLUME:Long,
                     RECENT_30_00_DOWN_VOLUME:Long,RECENT_30_01_DOWN_VOLUME:Long,RECENT_30_02_DOWN_VOLUME:Long,
                     RECENT_30_03_DOWN_VOLUME:Long,RECENT_30_04_DOWN_VOLUME:Long,RECENT_30_05_DOWN_VOLUME:Long,
                     RECENT_30_06_DOWN_VOLUME:Long,RECENT_30_07_DOWN_VOLUME:Long,RECENT_30_08_DOWN_VOLUME:Long,
                     RECENT_30_09_DOWN_VOLUME:Long,RECENT_30_10_DOWN_VOLUME:Long,RECENT_30_11_DOWN_VOLUME:Long,
                     RECENT_30_00_2G_UP_VOLUME:Long,RECENT_30_01_2G_UP_VOLUME:Long,RECENT_30_02_2G_UP_VOLUME:Long,
                     RECENT_30_03_2G_UP_VOLUME:Long,RECENT_30_04_2G_UP_VOLUME:Long,RECENT_30_05_2G_UP_VOLUME:Long,
                     RECENT_30_06_2G_UP_VOLUME:Long,RECENT_30_07_2G_UP_VOLUME:Long,RECENT_30_08_2G_UP_VOLUME:Long,
                     RECENT_30_09_2G_UP_VOLUME:Long,RECENT_30_10_2G_UP_VOLUME:Long,RECENT_30_11_2G_UP_VOLUME:Long,
                     RECENT_30_00_2G_DOWN_VOLUME:Long,RECENT_30_01_2G_DOWN_VOLUME:Long,RECENT_30_02_2G_DOWN_VOLUME:Long,
                     RECENT_30_03_2G_DOWN_VOLUME:Long,RECENT_30_04_2G_DOWN_VOLUME:Long,RECENT_30_05_2G_DOWN_VOLUME:Long,
                     RECENT_30_06_2G_DOWN_VOLUME:Long,RECENT_30_07_2G_DOWN_VOLUME:Long,RECENT_30_08_2G_DOWN_VOLUME:Long,
                     RECENT_30_09_2G_DOWN_VOLUME:Long,RECENT_30_10_2G_DOWN_VOLUME:Long,RECENT_30_11_2G_DOWN_VOLUME:Long,
                     RECENT_30_00_3G_UP_VOLUME:Long,RECENT_30_01_3G_UP_VOLUME:Long,RECENT_30_02_3G_UP_VOLUME:Long,
                     RECENT_30_03_3G_UP_VOLUME:Long,RECENT_30_04_3G_UP_VOLUME:Long,RECENT_30_05_3G_UP_VOLUME:Long,
                     RECENT_30_06_3G_UP_VOLUME:Long,RECENT_30_07_3G_UP_VOLUME:Long,RECENT_30_08_3G_UP_VOLUME:Long,
                     RECENT_30_09_3G_UP_VOLUME:Long,RECENT_30_10_3G_UP_VOLUME:Long,RECENT_30_11_3G_UP_VOLUME:Long,
                     RECENT_30_00_3G_DOWN_VOLUME:Long,RECENT_30_01_3G_DOWN_VOLUME:Long,RECENT_30_02_3G_DOWN_VOLUME:Long,
                     RECENT_30_03_3G_DOWN_VOLUME:Long,RECENT_30_04_3G_DOWN_VOLUME:Long,RECENT_30_05_3G_DOWN_VOLUME:Long,
                     RECENT_30_06_3G_DOWN_VOLUME:Long,RECENT_30_07_3G_DOWN_VOLUME:Long,RECENT_30_08_3G_DOWN_VOLUME:Long,
                     RECENT_30_09_3G_DOWN_VOLUME:Long,RECENT_30_10_3G_DOWN_VOLUME:Long,RECENT_30_11_3G_DOWN_VOLUME:Long,
                     RECENT_30_00_4G_UP_VOLUME:Long,RECENT_30_01_4G_UP_VOLUME:Long,RECENT_30_02_4G_UP_VOLUME:Long,
                     RECENT_30_03_4G_UP_VOLUME:Long,RECENT_30_04_4G_UP_VOLUME:Long,RECENT_30_05_4G_UP_VOLUME:Long,
                     RECENT_30_06_4G_UP_VOLUME:Long,RECENT_30_07_4G_UP_VOLUME:Long,RECENT_30_08_4G_UP_VOLUME:Long,
                     RECENT_30_09_4G_UP_VOLUME:Long,RECENT_30_10_4G_UP_VOLUME:Long,RECENT_30_11_4G_UP_VOLUME:Long,
                     RECENT_30_00_4G_DOWN_VOLUME:Long,RECENT_30_01_4G_DOWN_VOLUME:Long,RECENT_30_02_4G_DOWN_VOLUME:Long,
                     RECENT_30_03_4G_DOWN_VOLUME:Long,RECENT_30_04_4G_DOWN_VOLUME:Long,RECENT_30_05_4G_DOWN_VOLUME:Long,
                     RECENT_30_06_4G_DOWN_VOLUME:Long,RECENT_30_07_4G_DOWN_VOLUME:Long,RECENT_30_08_4G_DOWN_VOLUME:Long,
                     RECENT_30_09_4G_DOWN_VOLUME:Long,RECENT_30_10_4G_DOWN_VOLUME:Long,RECENT_30_11_4G_DOWN_VOLUME:Long
                    )

case class MonthSms(USER_NUMBER:String,RECENT_30_DAY_COUNT:Long,RECENT_30_COUNT:Long,
                    SMS_30_00_VOLUME:Long,	SMS_30_01_VOLUME:Long,	SMS_30_02_VOLUME:Long,
                    SMS_30_03_VOLUME:Long,	SMS_30_04_VOLUME:Long,	SMS_30_05_VOLUME:Long,
                    SMS_30_06_VOLUME:Long,	SMS_30_07_VOLUME:Long,	SMS_30_08_VOLUME:Long,
                    SMS_30_09_VOLUME:Long,	SMS_30_10_VOLUME:Long,	SMS_30_11_VOLUME:Long
                   )

case class MonthVoice(RECENT_30_DAY_COUNT:Long,RECENT_30_COUNT:Long,RECENT_30_CALL_COUNT:Long,
                      RECENT_30_CALLED_COUNT:Long,RECENT_30_CALL_VOLUME:Long,RECENT_30_CALLED_VOLUME:Long,
                      RECENT_30_CALL_00_COUNT:Long,RECENT_30_CALL_01_COUNT:Long,RECENT_30_CALL_02_COUNT:Long,
                      RECENT_30_CALL_03_COUNT:Long,RECENT_30_CALL_04_COUNT:Long,RECENT_30_CALL_05_COUNT:Long,
                      RECENT_30_CALL_06_COUNT:Long,RECENT_30_CALL_07_COUNT:Long,RECENT_30_CALL_08_COUNT:Long,
                      RECENT_30_CALL_09_COUNT:Long,RECENT_30_CALL_10_COUNT:Long,RECENT_30_CALL_11_COUNT:Long,
                      RECENT_30_CALLED_00_COUNT:Long,RECENT_30_CALLED_01_COUNT:Long,RECENT_30_CALLED_02_COUNT:Long,
                      RECENT_30_CALLED_03_COUNT:Long,RECENT_30_CALLED_04_COUNT:Long,RECENT_30_CALLED_05_COUNT:Long,
                      RECENT_30_CALLED_06_COUNT:Long,RECENT_30_CALLED_07_COUNT:Long,RECENT_30_CALLED_08_COUNT:Long,
                      RECENT_30_CALLED_09_COUNT:Long,RECENT_30_CALLED_10_COUNT:Long,RECENT_30_CALLED_11_COUNT:Long,
                      RECENT_30_CALL_00_VOLUME:Long,RECENT_30_CALL_01_VOLUME:Long,RECENT_30_CALL_02_VOLUME:Long,
                      RECENT_30_CALL_03_VOLUME:Long,RECENT_30_CALL_04_VOLUME:Long,RECENT_30_CALL_05_VOLUME:Long,
                      RECENT_30_CALL_06_VOLUME:Long,RECENT_30_CALL_07_VOLUME:Long,RECENT_30_CALL_08_VOLUME:Long,
                      RECENT_30_CALL_09_VOLUME:Long,RECENT_30_CALL_10_VOLUME:Long,RECENT_30_CALL_11_VOLUME:Long,
                      RECENT_30_CALLED_00_VOLUME:Long,RECENT_30_CALLED_01_VOLUME:Long,RECENT_30_CALLED_02_VOLUME:Long,
                      RECENT_30_CALLED_03_VOLUME:Long,RECENT_30_CALLED_04_VOLUME:Long,RECENT_30_CALLED_05_VOLUME:Long,
                      RECENT_30_CALLED_06_VOLUME:Long,RECENT_30_CALLED_07_VOLUME:Long,RECENT_30_CALLED_08_VOLUME:Long,
                      RECENT_30_CALLED_09_VOLUME:Long,RECENT_30_CALLED_10_VOLUME:Long,RECENT_30_CALLED_11_VOLUME:Long
                     )


case class Distance(USER_NUMBER:String,START_TIME:String,a1:Long,a2:Long,a3:Long,a4:Long,a5:Long,a6:Long,a7:Long,a8:Long,a9:Long,a10:Long,a11:Long,a12:Long,lastday:String,dist:Double)

